### PR TITLE
Fix logout button & redirects

### PR DESCRIPTION
**Pull request by Brod8362**
This fixes the logout button to be visible and not break the page when clicked.
Additionally, htmx redirects are now done with a 204 status code instead of 303 (as the browser would follow a 303 and htmx would not get to do the client-side redirect)
This addresses #22

### CODE REVIEW

**Comment by tnttruong** [comment]
image
This works perfectly, but results in the CSS looking kinda messed up without manually refreshing. Is it possible to use hx-refresh or am I misinterpreting how that works

**Comment by Brod8362** [comment]
Steps to reproduce?

**Comment by tnttruong** [comment]
Reproducible by login, then clicking the logout button

**Comment by Brod8362** [comment]
Works fine for me on both Firefox and Chrome, @Mnguyener @bbqcandy can one of you test it?

**Comment by Mnguyener** [comment]
Works fine for me on Firefox!

image

I didn't have to manually refresh at all.

**Review by Mnguyener — APPROVED** [review]
Looks good to me

**Pull request merged**
