### PR TITLE
fixed issues

### PR DESCRIPTION
**Pull request by bbqcandy**
removed extraneous fields from profile management page and fixed submit button

### CODE REVIEW

**Comment by Brod8362** [comment]
A few things:
- Please reference the IDs of the issues this addresses (you just reference them by their number, like this: #22 )
- In the future, one PR per issue
- Please have a title and description more involved than "fixed issues", describe not only *what* you fixed but *how* what you did addresses the fix.

**Review by Brod8362 — APPROVED** [review]
I want the others to get some experience doing code review & PR merges, I will approve this but not merge until at least one other person looks & approves

**Comment by bbqcandy** [comment]
> A few things:
> 
>     * Please reference the IDs of the issues this addresses (you just reference them by their number, like this: [Logout button jank #22](https://github.com/Brod8362/csoc4353/issues/22) )
> 
>     * In the future, one PR per issue
> 
>     * Please have a title and description more involved than "fixed issues", describe not only _what_ you fixed but _how_ what you did addresses the fix.

ok so tbh the only reason I did it as one PR instead of two was bc they were both  quick and easy fixes. For larger issues I would do two of them, and if u really think its necessary, I'll absolutley do it for small issues too in the fututre.

#19 and #18 did not know how to do this until right now. Also sorry for the vague description, but ig this would've helped as well.

**Review by Mnguyener — COMMENTED** [review]
Looks good! In the future, I think we should add red asterisks to visually mark which fields are required

**Pull request merged**
