### PR TITLE
made basic layout for webpages

### PR DESCRIPTION
**Pull request by tnttruong**
basic margins for website, logo is off-center for now because i can't figure out how to use float and object-position

### CODE REVIEW

**Comment by tnttruong** [comment]
image

**Comment by Brod8362** [comment]
Does it scale vertically up/down when you resize the window? e.g, Is the footer pinned to the bottom?

**Comment by tnttruong** [comment]
> Does it scale vertically up/down when you resize the window? e.g, Is the footer pinned to the bottom?

the footer isn't pinned to the bottom, just to the bottom of the context box. Only the sides move when the window is resized.

**Comment by Brod8362** [comment]
do you think we can implement the footer pinning in this PR? if not that's fine, it can come later

**Comment by tnttruong** [comment]
working on it right now

**Review by Brod8362 — APPROVED** [review]

**Pull request merged**
