### PR TITLE
wrote application design

### PR DESCRIPTION
**Pull request by tnttruong**

### CODE REVIEW

**Comment by Mnguyener** [comment]
What words are you adding to?

**Comment by Brod8362** [comment]
What about user authentication and accounts? And profile management? What will the experience look like for a new user from registration to fuel estimation?

**Comment by Mnguyener** [comment]
For user authentication, you should include that we will use salt and hash passwords with bcrypt. The flow would look something like: Register username + password -> Fill in additional profile info in the profile management -> Start fuel estimation

For profile management, explain that we will use Person type profiles that have the required client fields from assignment 2

**Review by bbqcandy — COMMENTED** [review]
Some small things I noticed:

- the user would have to register and ~login~ **log in** with the application... *i believe in this case you would want to use the term "log in" rather than "login" but that doesn't apply to all instances here* 
- This fuel rate will also be stored ~into~ in the database... *alternatively, you could also change it to "This fuel rate will also be **saved** into the database"*

**Review by Brod8362 — APPROVED** [review]

**Pull request merged**
